name: build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci

    - run: npm audit
      continue-on-error: true

    - run: npm run lint

    - run: npm run package

    - name: Check access
      if: ${{ github.event.pull_request.author_association != 'CONTRIBUTOR' && github.event.pull_request.author_association != 'MEMBER' }}
      run: |
        echo "Event not triggered by a collaborator."
        echo ${{ github.event.pull_request.author_association_association}}
        exit 1

    - run: |
        touch .env
        echo BING_KEY=${{ secrets.BING_KEY }} >> .env
        echo BING_KEY=${{ secrets.BING_KEY }}

    - run: npm run test
      env:
        CI: true